name: NodeJs App

on: [pull_request]
    # pull_request:
    #     branches:
    #         - develop
    #         - feature/*

jobs: 
    build:
        runs-on: ubuntu-latest

        strategy:
          matrix:
            node-version: ['15.x']

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: Setup NodeJS
              uses: actions/setup-node@v3
            - run: rm -rf node_modules && rm package-lock.json && npm cache clean -f && npm install
            - run: npm run lint
            - run: npm run prettier
            - run: CI=true npm run test
            - run: npm run build